spring.datasource.url=jdbc:postgresql://ep-icy-math-ai81s06w-pooler.c-4.us-east-1.aws.neon.tech/neondb?user=neondb_owner&password=npg_h1J8gkxXGUqN&sslmode=require&channelBinding=require
spring.datasource.username=neondb_owner
spring.datasource.password=PASTE_PASSWORD_HERE

spring.jpa.hibernate.ddl-auto=update
server.port=8081